# Generated by Django 4.0.4 on 2022-09-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peapp', '0003_truefalsequestion_textquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
